@startuml
start

:Получение аргументов командной строки;
if (Аргумент --fp1?) then (yes)
    :Сохранение пути к файлу 1;
    :Чтение данных из файла 1;
endif

if (Аргумент --fp2?) then (yes)
    :Сохранение пути к файлу 2;
    :Чтение данных из файла 2;
endif

if (Аргумент --op?) then (yes)
    if (Операция vv_sum?) then (yes)
        :Сложения векторов;
        :Вывод результата;
    else if (Операция vv_sub?) then (yes)
        :Вычитания векторов;
        :Вывод результата;
    else if (Операция vv_scMalt?) then (yes)
        :Скалярноое умножение;
        :Вывод результата;
    else (no)
        :Неизвестная операция;
    endif
else (no)
    :Вывод данных из файлов 1, 2;
endif

stop
@enduml